export const data = [
        {
          id_user: 1,
          name: 'João da Silva',
          email: 'joao@example.com',
          telefone: '(11) 98765-4321',
          userRole: 'ADMIN',
          status: true,
        },
        {
          id_user: 2,
          name: 'Maria Souza',
          email: 'maria@example.com',
          telefone: '(11) 91234-5678',
          userRole: 'User',
          status: false,
        },
        {
          id_user: 3,
          name: 'Pedro Santos',
          email: 'pedro@example.com',
          telefone: '(11) 92345-6789',
          userRole: 'User',
          status: true,
        },
        {
          id_user: 4,
          name: 'Ana Oliveira',
          email: 'ana@example.com',
          telefone: '(11) 93456-7890',
          userRole: 'Admin',
          status: false,
        },
        {
          id_user: 5,
          name: 'Mariana Costa',
          email: 'mariana@example.com',
          telefone: '(11) 94567-8901',
          userRole: 'User',
          status: true,
        },
        {
          id_user: 6,
          name: 'Carlos Pereira',
          email: 'carlos@example.com',
          telefone: '(11) 95678-9012',
          userRole: 'User',
          status: false,
        },
        {
          id_user: 7,
          name: 'Juliana Fernandes',
          email: 'juliana@example.com',
          telefone: '(11) 96789-0123',
          userRole: 'Admin',
          status: true,
        },
        {
          id_user: 8,
          name: 'Fernando Lima',
          email: 'fernando@example.com',
          telefone: '(11) 97890-1234',
          userRole: 'User',
          status: false,
        },
        {
          id_user: 9,
          name: 'Aline Rocha',
          email: 'aline@example.com',
          telefone: '(11) 98901-2345',
          userRole: 'User',
          status: true,
        },
        {
          id_user: 10,
          name: 'Ricardo Alves',
          email: 'ricardo@example.com',
          telefone: '(11) 99012-3456',
          userRole: 'Admin',
          status: false,
        },
        {
          id_user: 11,
          name: 'Patrícia Santos',
          email: 'patricia@example.com',
          telefone: '(11) 90123-4567',
          userRole: 'User',
          status: true,
        },
        {
          id_user: 12,
          name: 'Paulo Silva',
          email: 'paulo@example.com',
          telefone: '(11) 91234-5678',
          userRole: 'Admin',
          status: false,
        },
        {
          id_user: 13,
          name: 'Cristina Oliveira',
          email: 'cristina@example.com',
          telefone: '(11) 92345-6789',
          userRole: 'User',
          status: true,
        },
        {
          id_user: 14,
          name: 'Diego Costa',
          email: 'diego@example.com',
          telefone: '(11) 93456-7890',
          userRole: 'User',
          status: false,
        },
        {
          id_user: 15,
          name: 'Isabela Lima',
          email: 'isabela@example.com',
          telefone: '(11) 94567-8901',
          userRole: 'Admin',
          status: true,
        }
      
]